[versions]
agp = "8.9.0"
room = "2.5.1"
firebaseFirestore = "25.1.3"

[libraries]
#Android libraries
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
activity = { module = "androidx.activity:activity", version = "1.8.0" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
material = { module = "com.google.android.material:material", version = "1.10.0" }
room-runtime= { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler= { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing= { module = "androidx.room:room-testing", version.ref = "room" }
media3-common = { module = "androidx.media3:media3-common", version = "1.1.1" }

#Test libraries
junit = { module = "junit:junit", version = "4.13.2" }
ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }